---
title: "Tables"
output:
  html_document:
    toc: false
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
library(htmltools)
library(DT)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
table_one <- read_excel("data/Boundary_Management_Tables.xlsx", sheet=2)
table_two <- read_excel("data/Boundary_Management_Tables.xlsx", sheet=3)
table_three <- read_excel("data/Boundary_Management_Tables.xlsx", sheet=4)
```


### Table 1. *A Summary of Border and Boundary Theories*
```{r echo=FALSE}
table_one %>%
  DT::datatable(., 
              rownames = FALSE, 
              options = list(pageLength = 5, scrollX=T, scrollY=T))
```

### Table 2. *Scale Properties and Gaps Between Conceptus Definitions and Scale Items*
```{r echo=FALSE}
table_two %>%
  DT::datatable(., 
              rownames = FALSE, 
              options = list(pageLength = 5, scrollX=T, scrollY=T))
```

### Table 3. *The Measurement Taxonomy*
```{r echo=FALSE}
table_three %>%
  DT::datatable(rownames = FALSE, 
              options = list(pageLength = 5, scrollX=T, scrollY=T))
```