---
title: "Boundary Management Measurement Taxonomy"
output:
  html_document:
    toc: false
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

## Instructions

To explore the taxonomy interactively:

1. Select a scale domain.

2. Select a scale level

3. Select a scale construct.

4. Select a scale category.

5. Select a scale aspect.

You can also search the taxonomy via the table, below.

```{r message=FALSE, warning=FALSE, include=FALSE}
library(readxl)
library(tidyverse)
library(collapsibleTree)
library(htmltools)
library(DT)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
Domains <- read_excel("data/Measurement and Conceptual Taxonomy Table.xlsx", sheet=1)
Domains_Table <- read_excel("data/Measurement and Conceptual Taxonomy Table.xlsx", sheet=2)
```

### Interactive Taxonomy
```{r message=FALSE, warning=FALSE, echo=FALSE}
collapsibleTree(
  Domains,
  hierarchy = c("Scale Domain", 
                "Scale Level", 
                "Scale Construct",
                "Scale Category",
                "Scale Aspect",
                "Scale Title & Citation"
                ),
  width = 1200,
  zoomable = TRUE,
  tooltip = FALSE,
  collapsed = TRUE
)
```

### Searchable Taxonomy
```{r echo=FALSE}
DT::datatable(Domains_Table, 
              rownames = FALSE, 
              filter="top", 
              options = list(pageLength = 5, scrollX=T) )
```

